### ISSUE TITLE
Only 3 of 14 weights are showing up

### ISSUE THREAD

**Issue by voiceof** [cooperhewitt/cooperhewitt-typeface#4]
I'm on Windows 7, and after installing the typeface I can only see "light", "book" and "bold". All other weights are non-existent. When I look in the windows fonts folder I see cooper-hewitt light, book and 12 instances of bold.

I've see that a few others have had this issue but I haven't seen any solutions. Any ideas on how to work around this issue?

**Comment by pianomister** [comment]
Same for me. It seems that Windows 7 has an issue to recognize the font variants. All fonts here are named "Cooper Hewitt", and are differentiated only by font weight / variant property.

A solution would be to define the font variants as own families and name them "Cooper Hewitt Book", "Cooper Hewitt Light" etc. and give them the weight property "regular" each (resp. "italic" for their italic variants).
As an example of this naming convention, have a look at Exo 2 font which is working fine this way (e.g. available on fontsquirrel for free: http://www.fontsquirrel.com/fonts/exo-2). Not an elegant workaround, but works with Windows 7, tested in MS Word and Inkscape.

**Comment by impallari** [comment]
This is a bug in Windows soft, not in the font.... go complain to Microsoft :)

**Comment by Markus00000** [comment]
raphaelbastide:

>I confirm this issue.
>Tested in Inkscape and Libre Office Writer, linux.

impallari:

>This is a bug in Windows soft, not in the font.... go complain to Microsoft :)

**Comment by impallari** [comment]
Go complain Linux too :)

**Comment by impallari** [comment]
@Markus00000 
Inkscape v0.91 have been fixed!
"support for font faces beyond bold/italic;"
http://libregraphicsworld.org/blog/entry/inkscape-0-91-released

Again, it's not a bug in the fonts, it's a bug in the soft

**Comment by raphaelbastide** [comment]
This issue still exists on Inkscape v0.91 and Libre Office Writer 4.2.8.2.
![selection_026](https://cloud.githubusercontent.com/assets/193122/6023168/c8adfd64-abc2-11e4-867a-918c0b1e6bee.png)
In order to fix it on my local copy, can you tell me why exactly our programs interpret that Cooper Hewitt comes with 2 or 3 styles and not for other large fonts families?

**Comment by adrientetar** [comment]
It seems a problem with styleMapStyleName, for instance the Semibold has a "regular" stylemap while the otspec explicitly says only one font (the base one) in a given family should have this mapping.

**Comment by adrientetar** [comment]
Also italics have "regular" styleMapStyleName as well, they should really have italic instead.

**Comment by adrientetar** [comment]
> Again, it's not a bug in the fonts

Legacy ≠ bug.

**Comment by a8vam** [comment]
OK I found a solution finally for Windows users like me and for Adobe applications.

You have to copy the font files (or their shortcuts) to C:\Program Files (x86)\Common Files\Adobe\Fonts (if folder doesn't exist, create it) then restart the Adobe applications. That's it.

**Comment by nspringer** [comment]
> You have to copy the font files (or their shortcuts) to C:\Program Files (x86)\Common Files\Adobe\Fonts (if folder doesn't exist, create it) then restart the Adobe applications. That's it.

Unfortunately that didn't work for me in Illustrator or Photoshop

**Comment by nspringer** [comment]
~~Windows compatible version here: https://github.com/nspringer/cooper-hewitt-windows~~
Project removed until #1 resolved

**Comment by davelab6** [comment]
@nspringer sadly because https://github.com/cooperhewitt/cooperhewitt-typeface/issues/1 is not resolved you must change the names of your modified fonts

**Comment by nspringer** [comment]
Project removed until #1 resolved

**Comment by JerryCasiano** [comment]
All of these fonts have the same weight?

A simple solution is to set a proper weight for each instead of just 700 for all.

So, unless I'm missing something, the problem is with the fonts...

Edit - Removed information related to Fontconfig as it's not relevant. Sorry, forgot that Fontconfig maps standard weights to their own values.

**Comment by tilmanbremer** [comment]
So, its November 2016 now and I have the same error. The solution

> You have to copy the font files (or their shortcuts) to C:\Program Files (x86)\Common Files\Adobe\Fonts (if folder doesn't exist, create it) then restart the Adobe applications. That's it.
> didn't work for me either. Windows 8.1 here, trouble in all applications, but I would need the font mostly in Adobe products.
> I just see "Thin Italic", "Book" and "Bold".
> How is it possible that this error was reported 2 years ago and yet it is not even clear whose error it is?

**Comment by guilima** [comment]
Create subfolder with name "Fonts" in the Illustrator Application folder, exemple: C:\Program Files\Adobe\Adobe Illustrator CS6\Fonts, put in this folder some font files and restart Illustrator. Fonts now are included in the Illustrator font menu.

**Comment by hdellazeri** [comment]
Hey, guys. I finally found a solution that works on my PC. And it seems the problem was with the font.
Take a look here https://signs101.com/threads/cooper-hewitt-font-file-gripe.130421/. He explains that:

_I pulled all the font files into FontLab Studio 5. First I tried simply re-generating all the .otf files, thinking that might fix some possibly corrupted data. When bringing up the re-saved .otf files in Bitstream Font Navigator I noticed several of the font weights looked identical, thin yet named "bold." So I went back into FontLab and checked the Font Info for each weight. The font weight selections turned out to be not correctly specified. Nothing marked italic and everything listed as bold. It took a few minutes to carefully get the font styles marked correctly. Then I re-generated the .otf files. They worked properly._

I repeated the process here and reinstalled the fonts directly on Windows. They're working properly now.

I also saved them on my Dropbox, feel free to download and test on your computer: https://www.dropbox.com/s/jsj28a337z2ovr3/CooperHewitt_Windows.rar?dl=0.

Thank you! :)

**Comment by benforeva** [comment]
@hdellazeri this sorta worked for me. But I only have access to two weights at a time - a bold and regular weight. I can only access the bold weight via CTRL+B.

**Comment by shanahben** [comment]
@hdellazeri Thanks for sharing what you've done but, sadly, they're still not working for me. :(

**Comment by NewSta1** [comment]
I personally just converted the fonts to TTF using an online converter ( https://onlinefontconverter.com ) and that worked pretty well. (I used it with SF-Mono which I extracted from macOS Sierra's Terminal, but this should work with any other font, too)

**Comment by tom10271** [comment]
Hi @hdellazeri, I can't download the file you uploaded to Dropbox. Can you re-upload it again?

**Comment by tom10271** [comment]
https://github.com/tom10271/cooper-hewitt-fixed-for-windows/tree/master

For those who have real pain in the ___, here is the fixed font files. I think it should fix the problem we face in Windows and Linux. Please try.

Download here:
https://github.com/tom10271/cooper-hewitt-fixed-for-windows/archive/refs/tags/1.0.0.zip

**Comment by hdellazeri** [comment]
Great job! @tom10271 :)

I deleted the file from Dropbox and I don't remember how. Anyway, I have a new link here (just in case): https://drive.google.com/drive/folders/0BxkTOuLrHvhqUThCZXR0MU1wUUk?usp=sharing.

**Comment by Qkay** [comment]
Thank you very much hdellazeri, great job. its working perfectly now

**Comment by voneff** [comment]
Kudos to @tom10271 – your fix is working great! Why would they not fix this on the official website?

**Comment by abdallahkhaled26** [comment]
Thank you @tom10271 - Works perfectly on Windows 10 with Adobe Applications

**Comment by hendricmarmata** [comment]
It's December 04, 2020. and I still have same problem.
Thank you for @hdellazeri to regenerate those fonts

**Comment by medmedin2014** [comment]
> Go complain Linux too :)
> 
> The point is that the bug in not in the fonts. The but is in the soft, that assumes that fonts have 4 styles only (Reg, Bold, RegItalic, BoldItalic) and fails to manage bigger families with more styles.

So from where should we get a software that recognize your weird fonts ? From Mars ?

**Comment by rtbs-dev** [comment]
Just chiming in to say that @tom10271 and @hdellazeri fixed the issue I was having with Manjaro Linux (gnome) too. Ubuntu seemed to be working, but the Manjaro fonts were broken when used in CSS (everything was bold in my Quarto document, no matter which weight I used/set). These fixed all the issued.
